# Generated by Django 2.0.3 on 2018-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockStories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('open', models.IntegerField(default=0)),
                ('close', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
    ]
